# stockmaster_backend/inventory/urls.py
from django.urls import path
from .views import RegisterView, CustomTokenObtainPairView
from rest_framework_simplejwt.views import TokenRefreshView

urlpatterns = [
    # JWT Login/Token Endpoints
    path('auth/login/', CustomTokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('auth/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    
    # Registration Endpoint
    path('auth/register/', RegisterView.as_view(), name='auth_register'),
]

# stockmaster_backend/inventory/urls.py (Continued from Step 1.2)
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import (
    RegisterView, CustomTokenObtainPairView, 
    CategoryViewSet, ProductViewSet
)
from rest_framework_simplejwt.views import TokenRefreshView

# Create a router instance
router = DefaultRouter()

# Register the ViewSets
router.register(r'categories', CategoryViewSet) # Routes: /api/categories/, /api/categories/<id>/
router.register(r'products', ProductViewSet)   # Routes: /api/products/, /api/products/<id>/

urlpatterns = [
    # JWT Auth Endpoints
    path('auth/login/', CustomTokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('auth/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('auth/register/', RegisterView.as_view(), name='auth_register'),
    
    # Include the routes generated by the router
    path('', include(router.urls)),
]